/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ChangelogRouteImport } from "./routes/changelog";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DocsSlugRouteImport } from "./routes/docs.$slug";

const ChangelogRoute = ChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: "/docs/$slug",
  path: "/docs/$slug",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/changelog": typeof ChangelogRoute;
  "/docs/$slug": typeof DocsSlugRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/changelog": typeof ChangelogRoute;
  "/docs/$slug": typeof DocsSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/changelog": typeof ChangelogRoute;
  "/docs/$slug": typeof DocsSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/changelog" | "/docs/$slug";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/changelog" | "/docs/$slug";
  id: "__root__" | "/" | "/changelog" | "/docs/$slug";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChangelogRoute: typeof ChangelogRoute;
  DocsSlugRoute: typeof DocsSlugRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/$slug": {
      id: "/docs/$slug";
      path: "/docs/$slug";
      fullPath: "/docs/$slug";
      preLoaderRoute: typeof DocsSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  DocsSlugRoute: DocsSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
