/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.x. Running `npx convex dev` regenerates it.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
